In [1]:
import pandas as pd 
import numpy as np
df=pd.read_csv('iris.csv')
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [2]:
x=df[['sepal_length','sepal_width','petal_length','sepal_width']]
y=df[['species']]
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=40)

In [3]:
x_train

sepal_length  sepal_width  petal_length  sepal_width
62           6.0          2.2           4.0          2.2
23           5.1          3.3           1.7          3.3
26           5.0          3.4           1.6          3.4
48           5.3          3.7           1.5          3.7
2            4.7          3.2           1.3          3.2
..           ...          ...           ...          ...
71           6.1          2.8           4.0          2.8
12           4.8          3.0           1.4          3.0
50           7.0          3.2           4.7          3.2
7            5.0          3.4           1.5          3.4
70           5.9          3.2           4.8          3.2

[120 rows x 4 columns]

In [4]:
x_test

sepal_length  sepal_width  petal_length  sepal_width
38            4.4          3.0           1.3          3.0
66            5.6          3.0           4.5          3.0
115           6.4          3.2           5.3          3.2
117           7.7          3.8           6.7          3.8
89            5.5          2.5           4.0          2.5
136           6.3          3.4           5.6          3.4
68            6.2          2.2           4.5          2.2
94            5.6          2.7           4.2          2.7
84            5.4          3.0           4.5          3.0
28            5.2          3.4           1.4          3.4
90            5.5          2.6           4.4          2.6
11            4.8          3.4           1.6          3.4
40            5.0          3.5           1.3          3.5
126           6.2          2.8           4.8          2.8
79            5.7          2.6           3.5          2.6
144           6.7          3.3           5.7          3.3
123           6.3          2.7           4.9          2.7
124           6.7          3.3           5.7          3.3
76            6.8          2.8           4.8          2.8
59            5.2          2.7           3.9          2.7
132           6.4          2.8           5.6          2.8
105           7.6          3.0           6.6          3.0
53            5.5          2.3           4.0          2.3
17            5.1          3.5           1.4          3.5
64            5.6          2.9           3.6          2.9
18            5.7          3.8           1.7          3.8
13            4.3          3.0           1.1          3.0
116           6.5          3.0           5.5          3.0
9             4.9          3.1           1.5          3.1
81            5.5          2.4           3.7          2.4

In [5]:
y_test

species
38       setosa
66   versicolor
115   virginica
117   virginica
89   versicolor
136   virginica
68   versicolor
94   versicolor
84   versicolor
28       setosa
90   versicolor
11       setosa
40       setosa
126   virginica
79   versicolor
144   virginica
123   virginica
124   virginica
76   versicolor
59   versicolor
132   virginica
105   virginica
53   versicolor
17       setosa
64   versicolor
18       setosa
13       setosa
116   virginica
9        setosa
81   versicolor

In [6]:
y_train

species
62  versicolor
23      setosa
26      setosa
48      setosa
2       setosa
..         ...
71  versicolor
12      setosa
50  versicolor
7       setosa
70  versicolor

[120 rows x 1 columns]

In [7]:
from sklearn.tree import DecisionTreeClassifier
dfc = DecisionTreeClassifier()  
dfc.fit(x_train, y_train)  

DecisionTreeClassifier()

In [8]:
y_pred = dfc.predict(x_test)
y_pred

array(['setosa', 'versicolor', 'virginica', 'virginica', 'versicolor',
       'virginica', 'versicolor', 'versicolor', 'versicolor', 'setosa',
       'versicolor', 'setosa', 'setosa', 'virginica', 'versicolor',
       'virginica', 'versicolor', 'virginica', 'versicolor', 'versicolor',
       'virginica', 'virginica', 'versicolor', 'setosa', 'versicolor',
       'setosa', 'setosa', 'virginica', 'setosa', 'versicolor'],
      dtype=object)

In [9]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
acc=accuracy_score(y_test,y_pred)
print('accuracy:',acc)
cm= confusion_matrix(y_test,y_pred)
print('confusion_matrix:\n',cm)
cr=classification_report(y_test,y_pred)
print ('classification_report:',cr)

accuracy: 0.9666666666666667
confusion_matrix:
 [[ 8  0  0]
 [ 0 12  0]
 [ 0  1  9]]
classification_report:               precision    recall  f1-score   support

      setosa       1.00      1.00      1.00         8
  versicolor       0.92      1.00      0.96        12
   virginica       1.00      0.90      0.95        10

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30

